### ISSUE TITLE
[BUG]: Spyro: A Hero's Tail demo (SCUS-97456) crashes on boot

### ISSUE THREAD

**Issue by chaoticgd** [PCSX2/pcsx2#12040]
### Describe the Bug

The demo triggers [this assertion](https://github.com/PCSX2/pcsx2/blob/028e6cd8a81162f327cace8df1e30d0d0d7171d7/pcsx2/GS/Renderers/HW/GSTextureCache.cpp#L2657) on boot right after the intro video. I haven't bisected it but it seems likely to be related to [this commit](https://github.com/PCSX2/pcsx2/commit/3f7190e8844d08e1882bbdd9f0af5732543e24bc).

Note that it's that one demo disc that destroyed a bunch of people's memory cards.

### Reproduction Steps

- Boot the demo disc.
- Select the Spyro: A Hero's Tail demo.

Or use the attached GS dump.

### Expected Behavior

No crash.

### PCSX2 Revision

v2.3.31

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Ubuntu

### CPU

Intel i7 4790k

### GPU

NVIDIA GTX 970

### GS Settings

![Image](https://github.com/user-attachments/assets/a1c1f715-e0cb-4a99-83f4-68e689259bf5)

### Logs & Dumps

GS dump:
[PlayStation Underground - Holiday 2004 \[T-Rated\]_SCUS-97456_20241127150434.gs.zip](https://github.com/user-attachments/files/17936744/PlayStation.Underground.-.Holiday.2004.T-Rated._SCUS-97456_20241127150434.gs.zip)

Stack trace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140732402128448) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140732402128448) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140732402128448, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff5a5f476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff5a457f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555f215e6 in AbortWithMessage(char const*) (msg=0x633a <error: Cannot access memory at address 0x633a>, 
    msg@entry=0x7ffed0d63eb0 "/home/thomas/projects/pcsx2/pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2657: assertion failed in function bool GSTextureCache::PreloadTarget(GIFRegTEX0, const GSVector2i &, const GSVector2i &, bool, boo"...)
    at /home/thomas/projects/pcsx2/common/HostSys.cpp:136
#6  0x0000555555f184fc in pxOnAssertFail(char const*, int, char const*, char const*) (file=0x555555662713 "/home/thomas/projects/pcsx2/pcsx2/GS/Renderers/HW/GSTextureCache.cpp", line=line@entry=2657, func=<optimised out>, msg=<optimised out>)
    at /home/thomas/projects/pcsx2/common/Assertions.cpp:117
#7  0x0000555555c431b8 in GSTextureCache::PreloadTarget(GIFRegTEX0, GSVector2T<int> const&, GSVector2T<int> const&, bool, bool, bool, GSVector4i, GSTextureCache::Target*, GSTextureCache::Source*)
    (this=this@entry=0x7ffeb82fd410, TEX0=TEX0@entry=..., size=..., valid_size=..., is_frame=<optimised out>, preload=<optimised out>, preserve_target=<optimised out>, draw_rect=..., dst=0x7ffeba64a760, src=0x7ffebb95ff40)
    at /home/thomas/projects/pcsx2/pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2657
#8  0x0000555555c4376e in GSTextureCache::CreateTarget(GIFRegTEX0, GSVector2T<int> const&, GSVector2T<int> const&, float, int, bool, unsigned int, bool, bool, bool, GSVector4i, GSTextureCache::Source*)
    (this=<optimised out>, TEX0=..., size=..., valid_size=<optimised out>, scale=<optimised out>, type=<optimised out>, used=<optimised out>, fbmask=<optimised out>, is_frame=<optimised out>, preload=false, preserve_target=<optimised out>, draw_rect=..., src=<optimised out>)
    at /home/thomas/projects/pcsx2/pcsx2/GS/Renderers/HW/GSTextureCache.cpp:2359
#9  0x0000555555c21a8f in GSRendererHW::Draw() (this=0x7ffeb82f2ca0) at /home/thomas/projects/pcsx2/pcsx2/GS/Renderers/HW/GSRendererHW.cpp:2723
#10 0x0000555555b94af8 in GSState::FlushPrim() (this=this@entry=0x7ffeb82f2ca0) at /home/thomas/projects/pcsx2/pcsx2/GS/GSState.cpp:1728
#11 0x0000555555b90964 in GSState::Flush(GSState::GSFlushReason) (this=this@entry=0x7ffeb82f2ca0, reason=reason@entry=GSState::CLUTCHANGE) at /home/thomas/projects/pcsx2/pcsx2/GS/GSState.cpp:1496
#12 0x0000555555ba06df in GSState::ApplyTEX0<0>(GIFRegTEX0&) (this=0x7ffeb82f2ca0, TEX0=...) at /home/thomas/projects/pcsx2/pcsx2/GS/GSState.cpp:843
#13 0x0000555555b9d072 in GSState::GIFRegHandlerTEX0<0>(GIFReg const*) (this=0x633a, r=<optimised out>) at /home/thomas/projects/pcsx2/pcsx2/GS/GSState.cpp:992
#14 0x0000555555ba2bb5 in GSState::Transfer<3>(unsigned char const*, unsigned int) (this=0x7ffeb82f2ca0, mem=0x7ffff26ba2c0 " *A\341\205\376\a \006", size=<optimised out>) at /home/thomas/projects/pcsx2/pcsx2/GS/GSState.cpp:2416
#15 0x0000555555a8af83 in MTGS::MainLoop() () at /home/thomas/projects/pcsx2/pcsx2/MTGS.cpp:450
#16 MTGS::ThreadEntryPoint() () at /home/thomas/projects/pcsx2/pcsx2/MTGS.cpp:183
#17 0x0000555555f3c3e5 in std::function<void ()>::operator()() const (this=0x7fffe12d9a10) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:591
#18 Threading::Thread::ThreadProc(void*) (param=0x7fffe12d9a10) at /home/thomas/projects/pcsx2/common/Linux/LnxThreads.cpp:229
#19 0x00007ffff5ab1ac3 in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:442
#20 0x00007ffff5b43850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by lightningterror** [comment]
Tbh this is an issue only if you build dev/debug, as for the asserts I should've removed them but forgot since they are no longer needed.
