### ISSUE TITLE
Guilty Gear X2 - Freeze during gameplay

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#1810]
***PCSX2 version:***
`pcsx2-2017.02.08_213fa1c14_master-x86_64-1_git`
`mesa-compat32-2017.01.25_7c5629a269_master-x86_64-1_gitcompat32`

***PCSX2 options:***
It is hard to tell for sure, but I'm not sure any options affect it.

***Plugins used:***
`GSdx (GCC 5.4.0 SSE2/AVX) 1.1.0 [libGSdx]`

***Description of the issue:***
When playing arcade in Guilty Gear X2 I found that it will occasionally freeze (The game just stops), waiting around a minute at most and it will resume as if nothing happened. This has happened several times so far, but I have not found out exactly what triggers it and it doesn't seem to happen every time.

After some difficulties described in issue https://github.com/PCSX2/pcsx2/issues/1806 I was able to reproduce it while running pcsx2 in GDB where I then hit ctrl+c in the GDB terminal. I think this thread is the relevant one? Unfortunately I did not have debugging symbols for libdrm or mesa, I can try again if they prove important.
```
(gdb) thread 8
[Switching to thread 8 (Thread 0xeea02b40 (LWP 18445))]
#0  0xf68a40e4 in ioctl () from /lib/libc.so.6
(gdb) bt
#0  0xf68a40e4 in ioctl () from /lib/libc.so.6
#1  0xf6231804 in drmIoctl () from /usr/lib/libdrm.so.2
#2  0xf623464c in drmCommandWrite () from /usr/lib/libdrm.so.2
#3  0xf0905fda in nouveau_bo_wait () from /usr/lib/libdrm_nouveau.so.2
#4  0xf0906067 in nouveau_bo_map () from /usr/lib/libdrm_nouveau.so.2
#5  0xebf32ad8 in ?? () from /usr/lib/xorg/modules/dri/nouveau_dri.so
#6  0xebd63eb8 in ?? () from /usr/lib/xorg/modules/dri/nouveau_dri.so
#7  0xebaebbb2 in ?? () from /usr/lib/xorg/modules/dri/nouveau_dri.so
#8  0xeba494da in ?? () from /usr/lib/xorg/modules/dri/nouveau_dri.so
#9  0xebaf0976 in ?? () from /usr/lib/xorg/modules/dri/nouveau_dri.so
#10 0xeba4aca9 in ?? () from /usr/lib/xorg/modules/dri/nouveau_dri.so
#11 0xeba4aea8 in ?? () from /usr/lib/xorg/modules/dri/nouveau_dri.so
#12 0xf01ec308 in GSTextureOGL::Map (this=0xda91df08, m=..., _r=0xeea01d40, layer=0) at /tmp/SBo/pcsx2/plugins/GSdx/GSTextureOGL.cpp:409
#13 0xf01eaff1 in GSTextureCacheOGL::Read (this=0xee109048, t=0xdb7b94a0, r=...) at /tmp/SBo/pcsx2/plugins/GSdx/GSTextureCacheOGL.cpp:88
#14 0xf01e4659 in GSTextureCache::InvalidateLocalMem (this=0xee109048, off=0xe81eea00, r=...) at /tmp/SBo/pcsx2/plugins/GSdx/GSTextureCache.cpp:986
#15 0xf019cbf9 in GSRendererHW::InvalidateLocalMem (this=0xee1036c0, BITBLTBUF=..., r=..., clut=<optimized out>) at /tmp/SBo/pcsx2/plugins/GSdx/GSRendererHW.cpp:281
#16 0xf01cb9bd in GSState::Move (this=0xee1036c0) at /tmp/SBo/pcsx2/plugins/GSdx/GSState.cpp:1830
#17 0xf01e2a0a in GSState::Transfer<3> (this=0xee1036c0, mem=0xf3cdf820 "", mem@entry=0xf3cdf7e0 "\200", size=0, size@entry=5) at /tmp/SBo/pcsx2/plugins/GSdx/GSState.cpp:2146
#18 0xf012cba1 in GSgifTransfer (mem=0xf3cdf7e0 "\200", size=5) at /tmp/SBo/pcsx2/plugins/GSdx/GS.cpp:717
#19 0x080b4132 in SysMtgsThread::ExecuteTaskInThread (this=0xa717300 <mtgsThread>) at /tmp/SBo/pcsx2/pcsx2/MTGS.cpp:409
#20 0x08426aba in Threading::pxThread::_try_virtual_invoke (this=this@entry=0xa717300 <mtgsThread>, method=<optimized out>) at /tmp/SBo/pcsx2/common/src/Utilities/ThreadTools.cpp:543
#21 0x08428952 in Threading::pxThread::_internal_execute (this=this@entry=0xa717300 <mtgsThread>) at /tmp/SBo/pcsx2/common/src/Utilities/ThreadTools.cpp:639
#22 0x08428f6b in Threading::pxThread::_internal_callback (itsme=0xa717300 <mtgsThread>) at /tmp/SBo/pcsx2/common/src/Utilities/ThreadTools.cpp:680
#23 0xf6953612 in start_thread () from /lib/libpthread.so.0
#24 0xf68ae14e in clone () from /lib/libc.so.6
```
GDB log - http://pastebin.com/n8CFkVw4

***How to reproduce the issue:***
1. Start Arcade mode in Guilty Gear X2.
2. Play until it freezes (Or not...).

***Last known version to work:***
Given the difficulties in reproducing this I have not tried older versions thoroughly.

***PC specifications:***
CPU: `AMD 6350 FX`
GPU: `GTX 780Ti`
OS: `Slackware64-current`

**Comment by gregory38** [comment]
GSdx request a transfer from the GPU to the CPU. So the driver must flush all pending activities, and then do the transfer. It isn't fast but a freeze isn't normal. Just to be sure, what happen if you do
```
ctrl C
backtrace
continue (will resume execution)

And then repeat the 3 previous commands. Are you still frozen at the same place.
```

BTW, there is a fast texture invalidation hack. It will do smaller transfer so maybe it could avoid the freeze.

**Comment by orbea** [comment]
I got it to reproduce again with libdrm and mesa debugging symbols, Here is the backtrace of that thread again.
```
(gdb) thread 8
[Switching to thread 8 (Thread 0xeea02b40 (LWP 1910))]
#0  0xf68a40e4 in ioctl () from /lib/libc.so.6
(gdb) bt
#0  0xf68a40e4 in ioctl () from /lib/libc.so.6
#1  0xf61fab2f in drmIoctl (fd=fd@entry=23, request=request@entry=1074291842, arg=arg@entry=0xeea01868) at xf86drm.c:191
#2  0xf61fd786 in drmCommandWrite (fd=23, drmCommandIndex=drmCommandIndex@entry=66, data=data@entry=0xeea01868, size=size@entry=8) at xf86drm.c:2587
#3  0xf00b3c1e in nouveau_bo_wait (bo=bo@entry=0xdb5c9c38, access=access@entry=256, client=client@entry=0xee194a90) at nouveau.c:856
#4  0xf00b3cd3 in nouveau_bo_map (bo=0xdb5c9c38, access=256, client=0xee194a90) at nouveau.c:877
#5  0xebdaa0cc in nvc0_miptree_transfer_map (pctx=0xee14f478, res=0xdb5ded08, level=0, usage=1, box=0xeea01998, ptransfer=0xdbcecb5c) at nvc0/nvc0_transfer.c:456
#6  0xebb835f2 in u_transfer_map_vtbl (context=0xee14f478, resource=0xdb5ded08, level=0, usage=1, box=0xeea01998, transfer=0xdbcecb5c) at util/u_transfer.c:138
#7  0xeb8cdbaa in pipe_transfer_map (context=0xee14f478, resource=0xdb5ded08, level=0, layer=0, access=1, x=0, y=0, w=640, h=480, transfer=0xdbcecb5c)
    at ../../src/gallium/auxiliary/util/u_inlines.h:423
#8  0xeb8cefea in st_MapRenderbuffer (ctx=0xee1612b8, rb=0xdbcecb00, x=0, y=0, w=640, h=480, mode=1, mapOut=0xeea01a78, rowStrideOut=0xeea01a74) at state_tracker/st_cb_fbo.c:794
#9  0xeb7ee323 in readpixels_memcpy (ctx=0xee1612b8, x=0, y=0, width=640, height=480, format=6408, type=5121, pixels=0xdb0d3020, packing=0xeea01bdc) at main/readpix.c:234
#10 0xeb7efa0c in _mesa_readpixels (ctx=0xee1612b8, x=0, y=0, width=640, height=480, format=6408, type=5121, packing=0xeea01bdc, pixels=0xdb0d3020) at main/readpix.c:867
#11 0xeb8d4c38 in st_ReadPixels (ctx=0xee1612b8, x=0, y=0, width=640, height=480, format=6408, type=5121, pack=0xeea01bdc, pixels=0xdb0d3020) at state_tracker/st_cb_readpixels.c:545
#12 0xeb7f03f0 in _mesa_ReadnPixelsARB (x=0, y=0, width=640, height=480, format=6408, type=5121, bufSize=2147483647, pixels=0xdb0d3020) at main/readpix.c:1116
#13 0xeb7f044b in _mesa_ReadPixels (x=0, y=0, width=640, height=480, format=6408, type=5121, pixels=0xdb0d3020) at main/readpix.c:1124
#14 0xf01ec308 in GSTextureOGL::Map (this=0xdbceeac8, m=..., _r=0xeea01d40, layer=0) at /tmp/SBo/pcsx2/plugins/GSdx/GSTextureOGL.cpp:409
#15 0xf01eaff1 in GSTextureCacheOGL::Read (this=0xee1090a8, t=0xdb2d3800, r=...) at /tmp/SBo/pcsx2/plugins/GSdx/GSTextureCacheOGL.cpp:88
#16 0xf01e4659 in GSTextureCache::InvalidateLocalMem (this=0xee1090a8, off=0xe7bcce60, r=...) at /tmp/SBo/pcsx2/plugins/GSdx/GSTextureCache.cpp:986
#17 0xf019cbf9 in GSRendererHW::InvalidateLocalMem (this=0xee103720, BITBLTBUF=..., r=..., clut=<optimized out>) at /tmp/SBo/pcsx2/plugins/GSdx/GSRendererHW.cpp:281
#18 0xf01cb9bd in GSState::Move (this=0xee103720) at /tmp/SBo/pcsx2/plugins/GSdx/GSState.cpp:1830
#19 0xf01e2a0a in GSState::Transfer<3> (this=0xee103720, mem=0xf3d372a0 "\002", mem@entry=0xf3d37260 "\004\200", size=0, size@entry=5) at /tmp/SBo/pcsx2/plugins/GSdx/GSState.cpp:2146
#20 0xf012cba1 in GSgifTransfer (mem=0xf3d37260 "\004\200", size=5) at /tmp/SBo/pcsx2/plugins/GSdx/GS.cpp:717
#21 0x080b4132 in SysMtgsThread::ExecuteTaskInThread (this=0xa717300 <mtgsThread>) at /tmp/SBo/pcsx2/pcsx2/MTGS.cpp:409
#22 0x08426aba in Threading::pxThread::_try_virtual_invoke (this=this@entry=0xa717300 <mtgsThread>, method=<optimized out>) at /tmp/SBo/pcsx2/common/src/Utilities/ThreadTools.cpp:543
#23 0x08428952 in Threading::pxThread::_internal_execute (this=this@entry=0xa717300 <mtgsThread>) at /tmp/SBo/pcsx2/common/src/Utilities/ThreadTools.cpp:639
#24 0x08428f6b in Threading::pxThread::_internal_callback (itsme=0xa717300 <mtgsThread>) at /tmp/SBo/pcsx2/common/src/Utilities/ThreadTools.cpp:680
#25 0xf6953612 in start_thread () from /lib/libpthread.so.0
#26 0xf68ae14e in clone () from /lib/libc.so.6
```
GDB log -http://pastebin.com/DY8A7qwJ

I'm not sure I understand fully, but I tried to ctrl+c, backtrace and then continue a few times, the game always resumes normally and doesn't seem to get stuck again.

I'll try the fast texture invalidation hack next to see if I can reproduce it still.

**Comment by orbea** [comment]
So I tested the fast texture invalidation hack and was able to reproduce it, this time during the credits after completing the arcade mode. At this point I did nothing and after 30-60 seconds it resumed emulation normally.

**Comment by gregory38** [comment]
I'm afraid it is a driver bug. Maybe there is a timeout inside the kernel/driver, it could be limited to some GPU generation.

As a temporary workaround, you can try to hit F9 two time to toggle the renderer during the freeze. It could be faster than to wait 1 minute.

**Comment by orbea** [comment]
That is understandable, thanks for taking a look at it. This can be closed if you prefer, but if not I'd prefer to close if and when it is fixed in the driver. Perhaps a tag to specify its a driver specific issue would be a good idea?

**Comment by gregory38** [comment]
Yes, I will prefer to keep it open.

**Comment by orbea** [comment]
Do you happen to have an idea on how to reproduce this easily? It would probably be a good idea to see if this was a regression in the kernel, there were a few others in the new atomic code for 4.10. Otherwise I can try reproducing it in 4.9 a bit later...

**Comment by gregory38** [comment]
Unfortunately not. You can try to replay a gsdump in loop (there is an option) but I'm not sure it will work. It would be hard to capture the frame buffer read back as it happen very rarely.

**Comment by orbea** [comment]
I haven't seen this in a long time, I'm going to close this until I do see it again.
