### ISSUE TITLE
PCSX2 crashes while opening any GUI

### ISSUE THREAD

**Issue by arthurdead** [PCSX2/pcsx2#3607]
***PCSX2 version:***
1.7.0.r158.61f3258b9
installed from chaotic-aur/pcsx2-git

***Description of the issue:***
PCSX2 instantly crashes when opening any GUI

***PC specifications:***
Manjaro Linux x86-64

<details>
<summary>backtrace</summary>

```
Thread 1 "PCSX2" received signal SIGSEGV, Segmentation fault.
0xf68c731f in pango_renderer_part_changed () from /usr/lib32/libpango-1.0.so.0
(gdb) bt
#0  0xf68c731f in pango_renderer_part_changed () from /usr/lib32/libpango-1.0.so.0
#1  0xf68c75e5 in pango_renderer_set_alpha () from /usr/lib32/libpango-1.0.so.0
#2  0xf68c777f in ?? () from /usr/lib32/libpango-1.0.so.0
#3  0xf74a2d21 in ?? () from /usr/lib32/libgdk-x11-2.0.so.0
#4  0xf68cead1 in pango_renderer_draw_layout_line () from /usr/lib32/libpango-1.0.so.0
#5  0xf68cf68b in pango_renderer_draw_layout () from /usr/lib32/libpango-1.0.so.0
#6  0xf74a351e in gdk_draw_layout_with_colors () from /usr/lib32/libgdk-x11-2.0.so.0
#7  0xf74a37b7 in gdk_draw_layout () from /usr/lib32/libgdk-x11-2.0.so.0
#8  0xf711b2e7 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#9  0xf708bc68 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#10 0xf7098b51 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#11 0xf7553ac6 in g_closure_invoke () from /usr/lib32/libgobject-2.0.so.0
#12 0xf757cafb in ?? () from /usr/lib32/libgobject-2.0.so.0
#13 0xf756fd5c in g_signal_emit_valist () from /usr/lib32/libgobject-2.0.so.0
#14 0xf75709b5 in g_signal_emit () from /usr/lib32/libgobject-2.0.so.0
#15 0xf71c7c3d in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#16 0xf701438d in gtk_container_propagate_expose () from /usr/lib32/libgtk-x11-2.0.so.0
#17 0xf70143b5 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#18 0xf70129b0 in gtk_container_forall () from /usr/lib32/libgtk-x11-2.0.so.0
#19 0xf7012c1d in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#20 0xf6fe555c in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#21 0xf7098b51 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#22 0xf7553ac6 in g_closure_invoke () from /usr/lib32/libgobject-2.0.so.0
#23 0xf757cafb in ?? () from /usr/lib32/libgobject-2.0.so.0
#24 0xf756fd5c in g_signal_emit_valist () from /usr/lib32/libgobject-2.0.so.0
#25 0xf75709b5 in g_signal_emit () from /usr/lib32/libgobject-2.0.so.0
#26 0xf71c7c3d in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#27 0xf701438d in gtk_container_propagate_expose () from /usr/lib32/libgtk-x11-2.0.so.0
#28 0xf70143b5 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#29 0xf704f91d in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#30 0xf70129b0 in gtk_container_forall () from /usr/lib32/libgtk-x11-2.0.so.0
#31 0xf7012c1d in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#32 0xf7098b51 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#33 0xf7553ba6 in g_closure_invoke () from /usr/lib32/libgobject-2.0.so.0
#34 0xf757cafb in ?? () from /usr/lib32/libgobject-2.0.so.0
#35 0xf756fd5c in g_signal_emit_valist () from /usr/lib32/libgobject-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#36 0xf75709b5 in g_signal_emit () from /usr/lib32/libgobject-2.0.so.0
#37 0xf71c7c3d in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#38 0xf7096e8a in gtk_main_do_event () from /usr/lib32/libgtk-x11-2.0.so.0
#39 0xf74bb80b in ?? () from /usr/lib32/libgdk-x11-2.0.so.0
#40 0xf74bb7b7 in ?? () from /usr/lib32/libgdk-x11-2.0.so.0
#41 0xf74b74fe in ?? () from /usr/lib32/libgdk-x11-2.0.so.0
#42 0xf74b7fff in gdk_window_process_all_updates () from /usr/lib32/libgdk-x11-2.0.so.0
#43 0xf7012805 in ?? () from /usr/lib32/libgtk-x11-2.0.so.0
#44 0xf74932f7 in ?? () from /usr/lib32/libgdk-x11-2.0.so.0
#45 0xf67adb45 in g_main_context_dispatch () from /usr/lib32/libglib-2.0.so.0
#46 0xf67fcc12 in ?? () from /usr/lib32/libglib-2.0.so.0
#47 0xf67ac329 in g_main_loop_run () from /usr/lib32/libglib-2.0.so.0
#48 0xf7095750 in gtk_main () from /usr/lib32/libgtk-x11-2.0.so.0
#49 0xf78c97f6 in wxGUIEventLoop::DoRun() () from /usr/lib32/libwx_gtk2u_core-3.0.so.0
#50 0xf7d68932 in wxEventLoopBase::Run() () from /usr/lib32/libwx_baseu-3.0.so.0
#51 0xf7944ca4 in wxDialog::ShowModal() () from /usr/lib32/libwx_gtk2u_core-3.0.so.0
#52 0xf76a770d in wxWizard::RunWizard(wxWizardPage*) () from /usr/lib32/libwx_gtk2u_adv-3.0.so.0
#53 0x5674c2a1 in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
#54 0x5674cfa8 in ?? ()
#55 0x56752400 in ?? ()
#56 0xf7daf246 in wxEntry(int&, wchar_t**) () from /usr/lib32/libwx_baseu-3.0.so.0
#57 0x565e43fd in ?? ()
#58 0xf6aa6efe in __libc_start_main () from /usr/lib32/libc.so.6
#59 0x565e93c5 in ?? ()
```

</details>

**Comment by kenshen112** [comment]
Unfortunately Arch pushed a broken package with lib32pango. Unfortunately the only to resolve the issue currently is to downgrade the package
`sudo pacman -U https://archive.archlinux.org/packages/p/pango/lib32-pango-1%3A1.44.7-1-x86_64.pkg.tar.xz`

**Comment by arthurdead** [comment]
it works now thank you
