### ISSUE TITLE
x86_64: FolderMemoryCard::AddFileEntryToMetadataQuickAccess: segmentation fault

### ISSUE THREAD

**Issue by nE0sIghT** [PCSX2/pcsx2#3839]
***PCSX2 version:***
master: 2608673ca7f78ccacb16ac9ef5cd89f379f65f93

Trying to boot game with 64 bit version of PCSX2 after using 32 bit version previously I experience sigsegv:

```
#0  0x00007f61f56dd990 in raise () from /lib64/libpthread.so.0
#1  0x000055c601c3e015 in pxTrap () at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/common/src/Utilities/Exceptions.cpp:82
#2  0x000055c601c46b10 in SysPageFaultSignalFilter (signal=11, siginfo=0x7f61c8b4f770)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/common/src/Utilities/Linux/LnxHostSys.cpp:76
#3  <signal handler called>
#4  0x000055c601adc56f in FolderMemoryCard::AddFileEntryToMetadataQuickAccess (this=0x7f61c811e470, entry=0x7f61c4033244, parent=0x7f61c40492f8)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:563
#5  0x000055c601adbed8 in FolderMemoryCard::AddFile (this=0x7f61c811e470, dirEntry=0x7f61c403f394, dirPath=..., fileName=..., parent=0x7f61c40492f8)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:490
#6  0x000055c601adafe5 in FolderMemoryCard::AddFolder (this=0x7f61c811e470, dirEntry=0x7f61c403f394, dirPath=..., parent=0x7f61c40492f8, enableFiltering=false, filter=...)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:347
#7  0x000055c601adb60f in FolderMemoryCard::AddFolder (this=0x7f61c811e470, dirEntry=0x7f61c4032214, dirPath=..., parent=0x0, enableFiltering=true, filter=...)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:417
#8  0x000055c601ada6cf in FolderMemoryCard::LoadMemoryCardData (this=0x7f61c811e470, sizeInClusters=0, enableFiltering=true, filter=...)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:162
#9  0x000055c601ada145 in FolderMemoryCard::Open (this=0x7f61c811e470, fullPath=..., mcdOptions=..., sizeInClusters=0, enableFiltering=true, filter=..., simulateFileWrites=false)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:103
#10 0x000055c601ad9d92 in FolderMemoryCard::Open (this=0x7f61c811e470, enableFiltering=true, filter=...)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:63
#11 0x000055c601ae0d7b in FolderMemoryCardAggregator::Open (this=0x7f61c811e468)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFolder.cpp:1620
#12 0x000055c601ad80ad in FileMcd_EmuOpen (thisptr=0x7f61c811c010, session=0x0)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/MemoryCardFile.cpp:469
#13 0x000055c601869033 in SysCorePlugins::OpenPlugin_Mcd (this=0x55c60d607f40 <CorePlugins>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/PluginManager.cpp:1001
#14 0x000055c6018693a0 in SysCorePlugins::Open (this=0x55c60d607f40 <CorePlugins>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/PluginManager.cpp:1063
#15 0x000055c601a37965 in AppCorePlugins::Open (this=0x55c60d607f40 <CorePlugins>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/AppCorePlugins.cpp:343
#16 0x000055c601b5b849 in SysCoreThread::OnResumeInThread (this=0x55c60d608470 <CoreThread>, isSuspended=true)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/System/SysCoreThread.cpp:311
#17 0x000055c601a3c5f5 in AppCoreThread::OnResumeInThread (this=0x55c60d608470 <CoreThread>, isSuspended=true)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/AppCoreThread.cpp:576
#18 0x000055c601b5cdaf in SysThreadBase::StateCheckInThread (this=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/System/SysThreadBase.cpp:339
#19 0x000055c601b5b732 in SysCoreThread::StateCheckInThread (this=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/System/SysCoreThread.cpp:270
#20 0x000055c601a3c718 in AppCoreThread::StateCheckInThread (this=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/AppCoreThread.cpp:619
#21 0x000055c601b5b7d6 in SysCoreThread::ExecuteTaskInThread (this=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/System/SysCoreThread.cpp:294
#22 0x000055c601a3c7d4 in AppCoreThread::ExecuteTaskInThread (this=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/pcsx2/gui/AppCoreThread.cpp:635
#23 0x000055c601c55328 in Threading::pxThread::_try_virtual_invoke (this=0x55c60d608470 <CoreThread>, method=&virtual Threading::pxThread::ExecuteTaskInThread())
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/common/src/Utilities/ThreadTools.cpp:554
#24 0x000055c601c559d1 in Threading::pxThread::_internal_execute (this=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/common/src/Utilities/ThreadTools.cpp:650
#25 0x000055c601c55b3e in Threading::pxThread::internal_callback_helper (itsme=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/common/src/Utilities/ThreadTools.cpp:701
#26 0x000055c601c55aff in Threading::pxThread::_internal_callback (itsme=0x55c60d608470 <CoreThread>)
    at /mnt/media/portage/portage/games-emulation/pcsx2-9999-r1/work/pcsx2-9999/common/src/Utilities/ThreadTools.cpp:689
#27 0x00007f61f56d2e24 in start_thread () from /lib64/libpthread.so.0
#28 0x00007f61f563877f in clone () from /lib64/libc.so.6
```

**Comment by RedDevilus** [comment]
It's a known issue that software mode along with folder memorycards do not work in x64. Reason why the buildbot does not have it nor do we promote using it yet.

**Comment by nE0sIghT** [comment]
@RedDevilus 

> software mode

Could you please explain this part a bit more? I know "software mode" in terms of GPU plugin, but I don't think you are about it.
I want to switch Gentoo's git build to 64 bit, but I in doubt if memcards are portable between 32/64 bit builds.
Do I need to disable some cmake options to make build wich will works with 32 bit memcards?

**Comment by RedDevilus** [comment]
Yes im referring to the GSdx software renderer and for the memorycards, the file memorycards are cross-compatible. I'm not sure if you can compile only the memorycards as 32bit. Then again i don't use Linux as my main.

**Comment by nE0sIghT** [comment]
I never used software renderer with GSDX I beleave. Can it be different issue?

**Comment by RedDevilus** [comment]
It's possible but i don't deal with that issue. Tellowkrinkle can tell you about the x64 and kojin about GSdx. Lots of changes recently, hard to keep track off.

**Comment by nE0sIghT** [comment]
Here is my GSDX settings which works fine on 32 bit build (and same for 64 bit build).
I experience this crash with that settings:
![image](https://user-images.githubusercontent.com/3389586/96367174-26789700-115d-11eb-9825-01e1dd1a2f67.png)

**Comment by AmFobes** [comment]
Your crash is not related to GSDX. It is related to memory cards.
It is a known issue that memory cards do not work on the x64 build.
In order to use memory cards with pcsx2, you need to build an x86-32 bit pcsx2.

"I want to switch Gentoo's git build to 64 bit,"
DO NOT. 64 bit is _not_, I repeat _not_ fit for regular use. Consider it unstable.
