### ISSUE TITLE
[BUG]: Dynasty Warriors 2 / Shin Sangoku Musou - Garbage on post character selection screen with software rendering.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#4673]
### Describe the Bug

After choosing a character in Dynasty Warriors 2 / Shin Sangoku Musou, if you are using software rendering, the following screen is garbage. It displays properly with hardware/OGL rendering.

### Reproduction Steps

With software rendering on, get past the opening fmv (skip it with start, watch it all, doesn't matter) and choose any more. After you choose a character, the battle intro screen in question will play.

### Expected Behavior

I expected the post-character-select screen to be displayed properly on software rendering.

### PCSX2 Revision

PCSX2 1.7.0-20210817085737 - compiled on Aug 17 2021

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Uses an iGPU, see cpu

### GS Window Screenshots

Software rendering:
![image](https://user-images.githubusercontent.com/50224630/129777718-15a9d8da-3bda-44a9-a158-2f99f7e51ecc.png)
Hardware (OGL) rendering:
![image](https://user-images.githubusercontent.com/50224630/129777737-24a51065-80f9-4f2b-a3b1-21df9da246b2.png)

### Logs & Dumps

While I was unable to get log dumps here, I did get log dumps when I tested the game in Dobiestation. I will post them here in case they are useful.

`0x00005555555b6484 in GraphicsInterface::request_PATH(int, bool) ()
(gdb) bt
#0  0x00005555555b6484 in GraphicsInterface::request_PATH(int, bool) ()
#1  0x00005555555eaedc in VectorInterface::process_data_word(unsigned int) ()
#2  0x00005555555ec266 in VectorInterface::update(int) ()
#3  0x00005555555744bf in Emulator::run() ()
#4  0x00005555555d2ac3 in EmuThread::run() ()
#5  0x00007ffff6e8c9d2 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff6db4609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#7  0x00007ffff698e293 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`
    
Additionally, if this is also useful, Refraction mentioned that they suspected "Vif0 is trying to access the gif".

I'm sorry I couldn't provide logs from PCSX2; even after turning on everything nothing showed up. If there is anything additional I can do to get logs, please let me know.

**Comment by HeroponRikiBestest** [comment]
Forgot to add gsdumps initially.
[dumps.zip](https://github.com/PCSX2/pcsx2/files/7853204/dumps.zip)

**Comment by Mrlinkwii** [comment]
heres an updated GS dump , 
[issue 4673.zip](https://github.com/PCSX2/pcsx2/files/11169202/issue.4673.zip)



 SW mode is mostly the same 
![image](https://user-images.githubusercontent.com/17685135/230343767-55940189-1c41-43cb-b528-148f5fba3ef1.png)


HW mode is getting like SW mode 
![image](https://user-images.githubusercontent.com/17685135/230344080-b55df17a-dfdf-4a13-86e4-5f7101708cf5.png)

**Comment by HeroponRikiBestest** [comment]
Should the GS:Hardware tag be added, then?

**Comment by Mrlinkwii** [comment]
@HeroponRikiBestest  the game is very odd , if you boot in HW  and ever change renderer its fine , but if you boot in hw , change to software and back before the screen  its glitched in hw

**Comment by HeroponRikiBestest** [comment]
Ah, ok, so its possible nothing has actually changed?

**Comment by Mrlinkwii** [comment]
All I can say the game is doing odd stuff  :S

**Comment by michaelx333** [comment]
This happens in hardware too now. It's caused by a blur effect this screen has. I made this a while ago to disable the blur effect, which looks nicer than the bug:
(For ntsc-u version)
patch=1,EE,002C8668,word,00000000

It just nops a function that I believe is responsible for the effect.

Maybe devs can investigate the bug easier if they know where the blur function is located in code now.

**Comment by Buzzardsoul** [comment]
> This happens in hardware too now. It's caused by a blur effect this screen has. I made this a while ago to disable the blur effect, which looks nicer than the bug: (For ntsc-u version) patch=1,EE,002C8668,word,00000000
> 
> It just nops a function that I believe is responsible for the effect.
> 
> Maybe devs can investigate the bug easier if they know where the blur function is located in code now.

Can you test if this is any better?

patch=1,EE,00201984,word,00000000

**Comment by michaelx333** [comment]
> > This happens in hardware too now. It's caused by a blur effect this screen has. I made this a while ago to disable the blur effect, which looks nicer than the bug: (For ntsc-u version) patch=1,EE,002C8668,word,00000000
> > It just nops a function that I believe is responsible for the effect.
> > Maybe devs can investigate the bug easier if they know where the blur function is located in code now.
> 
> Can you test if this is any better?
> 
> patch=1,EE,00201984,word,00000000

Seems pretty much the same as mine.

**Comment by ScottNash042** [comment]
still happening on v2.7.10
