### ISSUE TITLE
[BUG]: Crash in Linux when opening a game after opening a gsdump after opening a game.

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#5316]
### Describe the Bug

On Linux, if you boot a game, close it (so resume is still an option), and try and run a gsdump, it'll give you an error.
![image](https://user-images.githubusercontent.com/50224630/148869167-7c977f84-4ca8-4dd0-a191-043bb2300eb0.png)
If you ignore it, close the gsdump, and then try and resume the game or boot a new game, the emulator will crash.
Backtrace:
```Thread 18 "MTGS" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7eff492d0700 (LWP 341750)]
0x0000564497a8a49f in GSreset () at /usr/include/c++/9/bits/unique_ptr.h:360
--Type <RET> for more, q to quit, c to continue without paging--
360          get() const noexcept
(gdb) bt
#0  0x0000564497a8a49f in GSreset() ()
    at /usr/include/c++/9/bits/unique_ptr.h:360
#1  0x000056449789fa4f in SysMtgsThread::ExecuteTaskInThread() (this=
    0x5644a4773aa0 <mtgsThread>) at ../pcsx2/MTGS.cpp:475
#2  0x0000564497dd527c in Threading::pxThread::_try_virtual_invoke(void (Threading::pxThread::*)()) (this=0x5644a4773aa0 <mtgsThread>, method=<optimized out>)
    at ../common/ThreadTools.cpp:571
#3  0x0000564497dd5f45 in Threading::pxThread::_internal_execute()
    (this=0x5644a4773aa0 <mtgsThread>) at ../common/ThreadTools.cpp:670
#4  0x0000564497dd61f3 in Threading::pxThread::internal_callback_helper(void*)
    (itsme=0x5644a4773aa0 <mtgsThread>) at ../common/ThreadTools.cpp:721
#5  0x0000564497dd6236 in Threading::pxThread::_internal_callback(void*)
    (itsme=<optimized out>) at ../common/ThreadTools.cpp:709
#6  0x00007eff60fed609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#7  0x00007eff60f14293 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95```

### Reproduction Steps

Outlined above.

### Expected Behavior

For the emulator not to crash.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2222 Compiled on Jan 10 2022

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20.2

**Comment by Mrlinkwii** [comment]
is this an issue on latest PCSX2 QT?

**Comment by MrCK1** [comment]
@HeroponRikiBestest Can you retry this on Qt?

**Comment by lightningterror** [comment]
Closing as this looks like it was a wx only issue.
