### ISSUE TITLE
Page fault at GSdx initialization:glGetString

### ISSUE THREAD

**Issue by Wesmania** [PCSX2/pcsx2#828]
Commit 2f9d5334ee (gsdx:EGL: prefer EGL over GLX + add some error messages) (found with git-bisect) introduces a page fault when loading a GSdx plugin. The output from the debug window is: 

```
/var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/common/src/Utilities/Linux/LnxHostSys.cpp(64) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t*, void*)
    Thread:    MTGS
    Condition: false
    Message:   Unhandled page fault @ 0x00000390

Stacktrace:
[00] __kernel_rt_sigreturn                       
[01] 0x0xf59972a6                                
[02] 0x0xef193af8                                
[03] 0x0xef2971df                                
[04] 0x0xef2aecd3                                
[05] 0x0xef175422                                
[06] GSopen2                                     
[07] SysMtgsThread::OpenPlugin()                  /portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/pcsx2/MTGS.cpp:192
[08] SysMtgsThread::OnResumeInThread(bool)        /portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/pcsx2/MTGS.cpp:567
[09] SysThreadBase::StateCheckInThread()          /portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/pcsx2/System/SysThreadBase.cpp:325
```

Attaching gdb produces additionally:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xed988b40 (LWP 22619)]
0xf59972a6 in glGetString () from /usr/lib32/opengl/nvidia/lib/libGL.so.1
(gdb) info threads
  Id   Target Id         Frame 
  5    Thread 0xf03ffb40 (LWP 22617) "EE Core" 0xf778eb90 in __kernel_vsyscall ()
* 4    Thread 0xed988b40 (LWP 22619) "MTGS" 0xf59972a6 in glGetString () from /usr/lib32/opengl/nvidia/lib/libGL.so.1
  3    Thread 0xf1818b40 (LWP 22570) "SysExecutor" 0xf778eb90 in __kernel_vsyscall ()
  2    Thread 0xf0dd3b40 (LWP 22572) "MTVU" 0xf778eb90 in __kernel_vsyscall ()
  1    Thread 0xf59f4980 (LWP 22553) "PCSX2" 0xf778eb90 in __kernel_vsyscall ()
(gdb) bt
#0  0xf59972a6 in glGetString () from /usr/lib32/opengl/nvidia/lib/libGL.so.1
#1  0xef146919 in GLLoader::check_gl_version (major=3, minor=3) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/plugins/GSdx/GLLoader.cpp:375
#2  0xef193af8 in GSDeviceOGL::Create (this=0xed002800, wnd=0xed038278) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/plugins/GSdx/GSDeviceOGL.cpp:183
#3  0xef2971df in GSRenderer::CreateDevice (this=0xed002ce0, dev=0xed002800) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/plugins/GSdx/GSRenderer.cpp:73
#4  0xef2aecd3 in GSRendererOGL::CreateDevice (this=0xed002ce0, dev=0xed002800) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/plugins/GSdx/GSRendererOGL.cpp:49
#5  0xef175422 in _GSopen (dsp=0x9ee158c <pDsp>, title=0x0, renderer=12, threads=0) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/plugins/GSdx/GS.cpp:435
#6  0xef17570a in GSopen2 (dsp=0x9ee158c <pDsp>, flags=1) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/plugins/GSdx/GS.cpp:492
#7  0x080b3571 in SysMtgsThread::OpenPlugin (this=0x9fd5930 <mtgsThread>) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/pcsx2/MTGS.cpp:192
#8  0x080b3e8f in SysMtgsThread::OnResumeInThread (this=0x9fd5930 <mtgsThread>, isSuspended=true) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/pcsx2/MTGS.cpp:567
#9  0x082ba845 in SysThreadBase::StateCheckInThread (this=0x9fd5930 <mtgsThread>) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/pcsx2/System/SysThreadBase.cpp:325
#10 0x080b36f4 in SysMtgsThread::ExecuteTaskInThread (this=0x9fd5930 <mtgsThread>) at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/pcsx2/MTGS.cpp:273
#11 0x08386bfe in Threading::pxThread::_try_virtual_invoke (this=0x9fd5930 <mtgsThread>, method=&virtual Threading::pxThread::ExecuteTaskInThread())
    at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/common/src/Utilities/ThreadTools.cpp:545
#12 0x083870af in Threading::pxThread::_internal_execute (this=0x9fd5930 <mtgsThread>)
    at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/common/src/Utilities/ThreadTools.cpp:644
#13 0x08387271 in Threading::pxThread::_internal_callback (itsme=0x9fd5930 <mtgsThread>)
    at /var/tmp/portage/games-emulation/pcsx2-9999-r2/work/pcsx2-9999/common/src/Utilities/ThreadTools.cpp:684
#14 0xf690dfeb in start_thread () from /lib32/libpthread.so.0
#15 0xf685650e in clone () from /lib32/libc.so.6
```

PCSX2 is compiled with DEGL_API=ON.

I'm using Gentoo Linux with kernel 4.0.5. I run PCSX2 through bumblebee, with nvidia closed driver version 352.30 and GeForce GTX 660M.

**Comment by gregory38** [comment]
Just don't run experimental option on experimental driver (as I'm not sure EGL implementation on Nvidia is fully stable)

**Comment by gregory38** [comment]
By the way, I think it must print some errors message if you run it from the terminal.

**Comment by Wesmania** [comment]
The only message in the console is:
```
EGL: Mesa Project : 1.4 (DRI2)
EGL: extensions supported: EGL_CHROMIUM_sync_control EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_KHR_create_context EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_NOK_swap_region EGL_NOK_texture_from_pixmap EGL_NV_post_sub_buffer
```
then SIGTRAP.

**Comment by gregory38** [comment]
Your issue is a mix of mesa (egl) and nvidia drivers (ogl)

**Comment by Wesmania** [comment]
Okay, thank you. Shouldn't it be possible to configure at runtime, though?

**Comment by gregory38** [comment]
Select what at runtime? Your driver installation is broken. EGL was never fully tested on GSdx. The only purpose of EGL is cross-OS-portability code. Reality is that windows/linux EGL implementations are bad

**Comment by Wesmania** [comment]
Okay. I'm sorry for the mess, compiling without the EGL flag selected the right backend. Closing.
